<? echo View::partial("consultorio/header_consultas",false,array("idhistoria"=>$idhistoria)) ?>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2">
            <? echo View::partial("consultorio/menu_consultas",false,array("idhistoria"=>$idhistoria)) ?>
        </div>
        <div class="span10">
            <table class="table table-bordered table-striped">
                <thead><tr style="text-align:center;font-weight:bold;">
                        <th>Id</th>
                        <th>Motivo consulta</th>
                        <th>Tratamiento</th>
                        <th>Fecha creación</th>
                        <th>Modificar</th>
                        <th>Eliminar</th>
                        <th>Remisión</th>
                        
                    </tr></thead>   
               
                <tbody>
                   <?foreach($consultas as $obj){?>
                    <tr>
                        <td><?echo $obj->id?></td>
                        <td><?echo $obj->motivoconsulta?></td>
                        <td><?echo $obj->tratamiento?></td>
                        <td><?echo $obj->creado_at?></td>
                        
                        <td><?echo Html::linkAction("modificar/$obj->id", Html::img("figuras/editar.png"))?></td>
                        <td>
                        <?echo Html::linkAction("eliminar/$obj->id", Html::img("figuras/eliminar.png"))?>
                        </td>
                        <td>
                         <?echo Html::link("remision/index/$obj->id", Html::img("figuras/remision.png"))?>   
                        </td>
                    </tr>
                   <?}?> 
                </tbody>
                 <tfoot>
                    <tr><th colspan="100"><div class="paginador-tabla"><span style="float:right;margin-right:20px;"><b>Total registros: 2</b></span></div></th></tr>
                </tfoot>
            </table> 
        </div>
    </div>
</div>
