<div id='cabecera' class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar pull-right" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand">Modulo de Administracion</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class='menu_admin_usuarios_perfil'><a href="/sistemas/backend/admin/usuarios/perfil"  >Mi Perfil</a>
                    </li>
                    <li class='menu_admin_usuarios_index dropdown'><a href="/sistemas/backend/admin/usuarios/index#" class="dropdown-toggle" data-toggle="dropdown" >Administración <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class='menu_admin_usuarios'><? echo Html::link("historia/index", "Historias")?>
                            </li>
                          
                        </ul>
                    </li>
                    <li class='menu_admin_usuarios_index dropdown'><a href="/sistemas/backend/admin/usuarios/index#" class="dropdown-toggle" data-toggle="dropdown" >Restricciones <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            
                            <li class='menu_admin_usuarios'><? echo Html::link("restricciones/restricciondia/index", "Restriccion dia")?>
                            </li>
                            <li class='menu_admin_usuarios'><? echo Html::link("restricciones/restricciondiahora/index", "Restriccion dia-hora")?>
                            </li>
                            <li class='menu_admin_usuarios'><? echo Html::link("restricciones/restriccionfecha/index", "Restriccion dia-hora")?>
                            </li>
                            <li class='menu_admin_usuarios'><? echo Html::link("restricciones/restriccionfechahora/index", "Restriccion dia-hora")?>
                            </li>
                            <li class='menu_admin_usuarios'><? echo Html::link("restricciones/restriccionhora/index", "Restriccion hora")?>
                            </li>
                        </ul>
                    </li>
                   
                </ul>
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="text-transform: capitalize;">
                            usuario administrador del sistema                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><?php echo Html::link("sesion/cerrar","Salir") ?></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
