<div id="accordion">
                          
    <h3><a href="#">Menú</a></h3>
    <div>
        <div><? echo Html::link("cita/nuevo/$idhistoria", "Nuevo") ?></div>
        <div><? echo Html::link("cita/index/$idhistoria", "Mostrar todos") ?></div>
         <div><? echo Html::link("historia/index/", "Volver") ?></div>
    </div>   
</div>

<script>
    $(function() {
        $( "#accordion" ).accordion();
    });
</script>